In [2]:
import numpy as np

In [7]:
# Shape of array
arr3 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr3)
print('Shape:', arr3.shape)

[[1 2 3]
 [4 5 6]]
Shape: (2, 3)


In [13]:
data = arr3.shape
print(data[0])
print(data[1])
print('Size:', data[0] * data[1])

2
3
Size: 6


In [14]:
# itemsize
arr3 = np.array([152, 10, 90], dtype = 'int32')
print(arr3)
print('Itemsize:', arr3.itemsize)

[152  10  90]
Itemsize: 4


In [25]:
arr4 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 9, 8], [11, 15, 0]]])
print(arr4)
print('Dimension:', arr4.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  9  8]
  [11 15  0]]]
Dimension: 3


In [26]:
arr4.argmax()

10

In [28]:
# accessing elements of 2D array
arr3 = np.array([[10, 20, 30], [40, 50, 60]])
print(arr3)
print('--------------------')
print(arr3[0, 2])

[[10 20 30]
 [40 50 60]]
--------------------
30


In [33]:
print(arr3[1, 1:3].max())

60


In [32]:
print(arr3[0:2, 0])

[10 40]


In [34]:
arr = np.empty([3,3], dtype = 'bool')
print(arr)

[[ True  True  True]
 [ True  True  True]
 [False False False]]


In [38]:
# eye
arr  = np.eye(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [41]:
numbers = list(range(5, 105, 5))

In [42]:
arr = np.array(numbers)
print(arr)

[  5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85  90
  95 100]


In [43]:
arr2D = np.array([[8, 7, 1, 2], [3, 2, 3, 1],
[29, 32, 11, 9]])
print(arr2D)
print('----------------')
arr2D.sort(axis=1)
print('Sorted Array : ')
print(arr2D)

[[ 8  7  1  2]
 [ 3  2  3  1]
 [29 32 11  9]]
----------------
Sorted Array : 
[[ 1  2  7  8]
 [ 1  2  3  3]
 [ 9 11 29 32]]


In [ ]:
# write a program takes the rows and columns and create an array accordingly. 
# The program should get the elements for that array also and then 
# find the index of maximum and minimum number of that array.