In [1]:
!pip install numpy

In [2]:
# Checking Numpy version
import numpy as np
print(np.__version__)

2.2.4


In [3]:
fruits = ['apple', 'mango', 'banana']
print('List:',fruits)
arr = np.array(fruits)
print('\nArray:', arr)

List: ['apple', 'mango', 'banana']

Array: ['apple' 'mango' 'banana']


In [4]:
fruits = ('apple', 'mango', 'banana')
arr2  = np.array(fruits)
print(arr2)

['apple' 'mango' 'banana']


In [5]:
arr3 = np.array([10, 20, 30, 40])
print(arr3)

[10 20 30 40]


In [6]:
print('Type of Array:', type(arr))

Type of Array: <class 'numpy.ndarray'>


In [7]:
arr = np.random.rand(2, 2)
print('\nRandom array:\n', arr)


Random array:
 [[0.76864426 0.43455723]
 [0.90665047 0.24185128]]


In [13]:
arr = np.random.randint(5, 15, size=(2, 3))  # From 5 to 14
print('\nRandom integers:\n', arr)


Random integers:
 [[13  9  7]
 [ 8 11  6]]
